MonsterHunterCompanion/Models/Palico/Bias.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MonsterHunterCompanion.Models.Palico
{
    /// <summary>
    ///  Can be one of: ....
    /// </summary>
    public class Bias
    {
        [Key]
        public int BiasId { get; set; }

        public string Name { get; set; }

        public int MaxSkillCost { get; set; }

        public virtual List<PalicoSkill> PalicoSkills { get; set; }

        public PalicoSkill PrimarySkill { get { return PalicoSkills.FirstOrDefault(x => x.SkillGroup.Group.Equals("P")); } }
    }
}

MonsterHunterCompanion/Models/Palico/Palico.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MonsterHunterCompanion.Models.Palico
{
    public class Palico
    {
        [Key]
        public int PalicoId { get; set; }

        public string Name { get; set; }

        public int Level { get; set; }
        // A bit annoying that I need to specify the column names for foreign keys 
        // If I don't want to use the default table_key
        public int BiasId { get; set; }

        // Get primary skill

        // Get secondary skill

        [ForeignKey("BiasId")]
        public virtual Bias Bias { get; set; }

        public virtual IEnumerable<PalicoSkill> Skills { get; set; }

        [NotMapped]
        public IEnumerable<PalicoSkill> PassiveSkills {
            get
            {
                return Skills.Where(x => x.Name.Equals("Passive"));
            }
        }

        [NotMapped]
        public IEnumerable<PalicoSkill> SupportSkills {
            get
            {
                return Skills.Where(x => x.Name.Equals("Support"));
            }
        }
    }
}

MonsterHunterCompanion/Models/Palico/PalicoSkill.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MonsterHunterCompanion.Models.Palico
{
    public class PalicoSkill
    {
        [Key]
        public int PalicoSkillId { get; set; }

        public string Name { get; set; }

        public int SkillTypeId { get; set; }

        public int SkillGroupId { get; set; }

        // Add in Bias later, for Primary Skills
        public int? BiasId { get; set; }

        [ForeignKey("BiasId")]
        public virtual Bias Bias { get; set; }

        [ForeignKey("SkillTypeId")]
        public virtual SkillType SkillType { get; set; }

        [ForeignKey("SkillGroupId")]
        public virtual SkillGroup SkillGroup { get; set; }
    }
}

MonsterHunterCompanion/Models/Palico/PalicoSkillMapping.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MonsterHunterCompanion.Models.Palico
{
    public class PalicoSkillMapping
    {
        public int PalicoId { get; set; }

        public int PalicoSkillId { get; set; }

        [Key, Column(Order=0)]
        [ForeignKey("PalicoId")]
        public virtual Palico Palico { get; set; }

        [Key, Column(Order = 1)]
        [ForeignKey("PalicoSkillId")]
        public virtual PalicoSkill PalicoSkill { get; set; }
    }
}

MonsterHunterCompanion/Models/Palico/Setting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MonsterHunterCompanion.Models.Palico
{
    public class Setting
    {
        [Key]
        public int SettingId { get; set; }

        public string Name { get; set; }

        public string Value { get; set; }
    }
}

MonsterHunterCompanion/Models/Palico/SkillGroup.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MonsterHunterCompanion.Models.Palico
{
    public class SkillGroup
    {
        [Key]
        public int SkillGroupId { get; set; }

        [StringLength(1), Column(TypeName = "char")]
        public string Group { get; set; }

        public string GroupDescription { get; set; }

        public int Cost { get; set; }
    }
}

MonsterHunterCompanion/Models/Palico/SkillPattern.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MonsterHunterCompanion.Models.Palico
{
    public class SkillPattern
    {
        [Key]
        public int SkillPatternId { get; set; }

        public virtual List<SkillPatternItem> SkillPatternList { get; set; }
    }
}

MonsterHunterCompanion/Models/Palico/SkillPatternItem.cs
using MonsterHunterCompanion.Models.Palico;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MonsterHunterCompanion.Models.Palico
{
    public class SkillPatternItem
    {
        [Key]
        public int SkillPatternItemId { get; set; }

        public int SkillPatternId { get; set; }

        public int SkillGroupId { get; set; }

        [ForeignKey("SkillPatternId")]
        public virtual SkillPattern SkillPattern { get; set; }

        [ForeignKey("SkillGroupId")]
        public virtual SkillGroup SkillGroup { get; set; }
    }
}

MonsterHunterCompanion/Models/Palico/SkillType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MonsterHunterCompanion.Models.Palico
{
    public class SkillType
    {
        [Key]
        public int SkillTypeId { get; set; }

        public string Name { get; set; }
    }
}

MonsterHunterCompanion/Models/Palico/Village.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MonsterHunterCompanion.Models.Palico
{
    public class Village
    {
        [Key]
        public int VillageId { get; set; }

        public string Name { get; set; }
    }
}

MonsterHunterCompanion/Models/Palico/VillageProbability.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MonsterHunterCompanion.Models.Palico
{
    public class VillageProbability
    {
        [Key]
        public int VillageProbabilityId { get; set; }

        public decimal Probability { get; set; }

        public int VillageId { get; set; }

        public int PalicoSkillId { get; set; }

        [ForeignKey("VillageId")]
        public virtual Village Village { get; set; }

        [ForeignKey("PalicoSkillId")]
        public virtual PalicoSkill PalicoSkill { get; set; } 
    }
}

MonsterHunterCompanion/Models/ViewModels/Palico/FurColours.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MonsterHunterCompanion.Models.ViewModels.Palico
{
    public class FurColours
    {
        public string MarkingColour { get; set; }

        public string EyeColour { get; set; }

        public string BaseColour { get; set; }
    }
}

MonsterHunterCompanion/Models/ViewModels/Palico/PalicoCompanionViewModel.cs
using MonsterHunterCompanion.Models.Palico;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MonsterHunterCompanion.Models.ViewModels.Palico
{
    public class PalicoCompanionViewModel
    {
        public PalicoCompanionViewModel()
        {
            SupportSkills = new SkillList();
            PassiveSkills = new SkillList();
        }

        public string Name { get; set; }

        public int Level { get; set; }

        public int BiasId { get; set; }

        public List<SelectListItem> Biases { get; set; }

        public Dictionary<string, decimal> VillageProbabilities { get; set; }

        public SkillList SupportSkills { get; set; }

        public SkillList PassiveSkills { get; set; }
    }
}

MonsterHunterCompanion/Models/ViewModels/Palico/SavedPalico.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MonsterHunterCompanion.Models.ViewModels.Palico
{
    public class SavedPalico
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public int Level { get; set; }

        public int BiasId { get; set; }

        public FurColours FurColours { get; set; }

        public SkillList SupportSkills { get; set; }

        public SkillList PassiveSkills { get; set; }
    }
}

MonsterHunterCompanion/Models/ViewModels/Palico/SkillList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MonsterHunterCompanion.Models.ViewModels.Palico
{
    public class SkillList
    {
        public SkillList()
        {
            AvailableSkills = new List<SelectListItem>();
            SelectedSkills = new List<SelectListItem>();
        }

        public int SelectedSkillId { get; set; }

        public string SkillType { get; set; }

        public List<SelectListItem> AvailableSkills { get; set; }

        public List<SelectListItem> SelectedSkills { get; set; }

        public int CarouselIndex { get; set; }
    }
}

MonsterHunterCompanion/Controllers/PalicoCompanionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MonsterHunterCompanion.Models.Palico;
using MonsterHunterCompanion.Models;
using MonsterHunterCompanion.Controllers.Builders.Interfaces;
using MonsterHunterCompanion.Controllers.Builders;
using MonsterHunterCompanion.Models.ViewModels.Palico;
using MonsterHunterCompanion.PalicoProbabilityFinder;
using Newtonsoft.Json;

namespace MonsterHunterCompanion.Controllers
{
    public class PalicoCompanionController : Controller
    {
        private MonsterHunterCompanionDBContext _context;

        private readonly IPalicoCompanionViewModelBuilder _viewModelBuilder;

        public PalicoCompanionController()
        {
            _context = new MonsterHunterCompanionDBContext();
            _viewModelBuilder = new PalicoCompanionViewModelBuilder();
        }
        //
        // GET: /PalicoProbabilityFinder/

        public ActionResult Index()
        {
            var probabilityQueryHandler = new PalicoProbabilityQueryHandler();
            var bias = new Bias()
            {
                MaxSkillCost = 8,
                Name = "Assisting"
            };

          
            var skills = _context.PalicoSkills.Where(x => x.Name.Equals("Big Boomerang")).ToList();
          //  skills.Add(_context.PalicoSkills.Where(x => x.Name.Equals("Ultrasonic Horn")).FirstOrDefault());
           // skills.Add(_context.PalicoSkills.Where(x => x.Name.Equals("Explosive Roll")).FirstOrDefault());
          //  skills.Add(_context.PalicoSkills.Where(x => x.Name.Equals("Bounce Bombay")).FirstOrDefault());
            
           // var optionalSkills = _context.PalicoSkills.Where(x => x.Name.Equals("Parting Gift")).ToList();
         //   optionalSkills.Add(_context.PalicoSkills.Where(x => x.Name.Equals("Soothing Roll")).First());
             skills.Add(_context.PalicoSkills.Where(x => x.Name.Equals("Critical Up S")).FirstOrDefault());
             skills.Add(_context.PalicoSkills.Where(x => x.Name.Equals("Boomerang Pro")).FirstOrDefault());
             skills.Add(_context.PalicoSkills.Where(x => x.Name.Equals("Earplugs")).FirstOrDefault());
            skills.Add(_context.PalicoSkills.Where(x => x.Name.Equals("Piercing Boomerang")).FirstOrDefault());
           // skills.Add(_context.PalicoSkills.Where(x => x.Name.Equals("Pitfall Purr-ison")).FirstOrDefault());
            // For big boom, crit up s, boom pro, earplugs and piercing (for assist of fighting) probability is:
            // Bherna 0.0025, Kokoto 0.0198, Pokke 0.00061, Yukomo 0.00068
            /*var optionalSkills = _context.PalicoSkills.Where(x => x.Name.Equals("Parting Gift")).ToList();
             optionalSkills.Add(_context.PalicoSkills.Where(x => x.Name.Equals("Soothing Roll")).First());*/
            // After fix, next thing to try is 13 - 1 , and an optional skill. Should also be probabaility of 1
            // No because if there's only 1 optional skill, it's required. Must be a pool of 2+
            //actualTotalProb = 0.0007025833430249300724153543 optional
            /*var probability = probabilityQueryHandler.FindProbabilityForVillages(new PalicoProbabilityQuery()
            {
                Bias = bias,
                Skills = skills/*,
                OptionalSkills = optionalSkills
            });

            var totalProb = 1M;
            foreach(var thing in probability.Values)
            {
                totalProb = (totalProb * 1M - thing);
            }
            var actualTotalProb = 1M - totalProb;
   
            */
            return View(_viewModelBuilder.Build(_context));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(PalicoCompanionViewModel model)
        {
            return View(_viewModelBuilder.Build(_context));
        }

        [HttpPost]
        public ActionResult CalculateProbabilities(PalicoCompanionViewModel model)
        {
            var probabilityQueryHandler = new PalicoProbabilityQueryHandler();
            var skillIds = model.SupportSkills.SelectedSkills.Select(x => Int32.Parse(x.Value)).ToList();
            skillIds.AddRange(model.PassiveSkills.SelectedSkills.Select(x => Int32.Parse(x.Value)));

            var query = new PalicoProbabilityQuery()
            {
                Bias = _context.Biases.First(x => x.BiasId == model.BiasId),
                Skills = _context.PalicoSkills.Where(x => skillIds.Contains(x.PalicoSkillId)).ToList(),
            };

            var probability = probabilityQueryHandler.FindProbabilityForVillages(query);

            return View("_villageProbabilities", probability);
        }

        [HttpPost]
        public ActionResult Populate(PalicoCompanionViewModel model)
        {
            return View("Index", model);
        }

        public bool AddSkill(int skillToAdd, PalicoCompanionViewModel model)
        {
            return false;
        }
    }
}

MonsterHunterCompanion/Views/PalicoCompanion/Index.cshtml
@model MonsterHunterCompanion.Models.ViewModels.Palico.PalicoCompanionViewModel

@{
    ViewBag.Title = "Palico Companion";
}



@using (Html.BeginForm(null, null, FormMethod.Post, new { id = "palicoForm"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
        <div class="container">
            <div class="row">

            </div>
            <div class="row" >
                <div class="col s6">
                    <div class="input-field col s12 m8">
                        <i class="material-icons prefix">
                            <img class="responsive-img" src="~/Images/PalicoIcons/Palico_Icon_White.png" />
                        </i>
                        @Html.LabelFor(m => m.Name)
                        @Html.EditorFor(m => m.Name)
                    </div>
                    <div class="input-field col s12 m4">
                        @Html.LabelFor(m => m.Level)
                        @Html.EditorFor(m => m.Level)
                    </div>
                    <div class="input-field col s12">
                   @Html.DropDownListFor(m => m.BiasId, Model.Biases, new { @class = "select-dropdown" })

                    @Html.Label("Support Bias")
                    </div>
                    @{Html.RenderPartial("_availableSkills", Model.SupportSkills);}
                    @{Html.RenderPartial("_availableSkills", Model.PassiveSkills);}
                </div>
                <div class="col s6">
                    <div class="carousel carousel-slider center" data-indicators="true">
                        <div class="carousel-item" href="#one!">
                            @Html.Label("Support Skills")
                            @{Html.RenderPartial("_selectedSkills", Model.SupportSkills.SkillType);}
                        </div>
                        <div class="carousel-item" href="#two!">
                            @Html.Label("Passive Skills")
                            @{Html.RenderPartial("_selectedSkills", Model.PassiveSkills.SkillType);}
                        </div>
                        <div class="carousel-item" href="#two!">
                            @Html.Label("Village Probabilities")
                            <div id="villageProbabilties">
                                @{Html.RenderPartial("_villageProbabilities", new Dictionary<string, decimal>());}
                            </div>
                        </div>
                        <div class="carousel-item" href="#three!">
                            @Html.Label("Your Palico")
                            <div id="palico">
                                @{Html.RenderPartial("_palico");}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @for (int i = 0; i < Model.Biases.Count; i++)
            {
                @Html.HiddenFor(m => Model.Biases[i].Text);
                @Html.HiddenFor(m => Model.Biases[i].Value);
            }
            <div class="row">
                <div class="col s12">
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Submit
                        <i class="material-icons right">send</i>
                    </button>
                    <a id="savePalico" class="btn-floating waves-effect waves-light inline"><i class="material-icons">add</i></a>
                </div>
            </div>
        </div>
    
}
<script language="javascript">

    var sortOptions = function (options) {
        var arr = options.map(function (_, o) { return { t: $(o).text(), v: o.value }; }).get();
        arr.sort(function (o1, o2) { return o1.t > o2.t ? 1 : o1.t < o2.t ? -1 : 0; });
        options.each(function (i, o) {
            o.value = arr[i].v;
            $(o).text(arr[i].t);
        });
    }

    
    var PopulateForm = function (data) {
        $.ajax({
            url: "@Url.Action("Populate", "PalicoCompanion")",
            type: "POST",
            data: data,
            cache: false,

            success: function (result) {
               // $("#palicoForm").html(result); Will add back in once i have an 'initialised' flag to avoid infinite loop
            }
        })
    };

    $(document).ready(function () {
        var data = localStorage.form;
        if(data != "")
        {
            PopulateForm(data);
        }
     
        
        $("#savePalico").click(function () {
            localStorage.form = $('#palicoForm').serialize();
            PopulateForm(localStorage.form);
        });
    });
        
</script>

MonsterHunterCompanion/Views/PalicoCompanion/_availableSkills.cshtml
@model MonsterHunterCompanion.Models.ViewModels.Palico.SkillList

<div class="input-field col s12 m11">
    
    @Html.DropDownListFor(m => Model.SelectedSkillId, Model.AvailableSkills, new { id = Model.SkillType + "SkillList" })
    @{
        var addButtonId = "add" + Model.SkillType + "Skill";
        var label = Model.SkillType + " Skills";
    }
    @*<input id="@addButtonId" type="button" value="Add">*@
    @Html.Label(@label)
</div>
<div class="input-field col s12 m1">
    <a id="@addButtonId" class="btn-floating waves-effect waves-light inline"><i class="material-icons">add</i></a>
    </div>

<script language="javascript">
    $(document).ready(function () {
        var skillType = "@Model.SkillType";
        var options = $('#' + skillType + 'SkillList option');
        sortOptions(options);

        $("#add" + skillType + "Skill").click(function () {
            $.ajax({
                url: "@Url.Action("AddSkill", "PalicoCompanion")",
                cache: false,
                data: { skillToAdd: $("#" + skillType + "SkillList").val(),  equipped: $("#palicoForm").serialize() },
                success: function (result) {
                    var skillName = $("#" + skillType + "SkillList :selected").text();
                    var skillId = $("#" + skillType + "SkillList").val();
                    $("#" + skillType + "SkillList :selected").remove();
                    $("#" + skillType + "Skills").append('<div id=selectedSkill' + skillType + skillId + '>' +
                        '<input name="' + skillType + 'Skills.SelectedSkills.Index" type="hidden" value="' + skillId + '">'
                        + '<input id="' + skillType + 'Skills_' + skillId + '__Value" name="' + skillType + 'Skills.SelectedSkills[' + skillId + '].Value" type="hidden" value="' + skillId + '">'
                        + '<input id="' + skillType + 'Skills_' + skillId + '__Text" name="' + skillType + 'Skills.SelectedSkills[' + skillId + '].Text" type="hidden" value="' + skillName + '">'
                    + '</div>')
                    $("#" + skillType + "Equipped").append('<li id=listItem' + skillType + skillId + '><div class="collection-item dismissable left-align">' + skillName + ''
                      + '<a href="#!" id=' + skillType + skillId + 'Remove class="secondary-content"><i class="material-icons">close</i></a></div></li>')
                    @*  + '<div class="collapsible-body left-align"><input type="checkbox" id =optionalCheck' + skillId + '>'
                        + '<label for="optionalCheck' + skillId + '">Optional</label></div></li>')*@
                    $("#" + skillType + skillId + "Remove").click(function () {
                        $("#selectedSkill" + skillType + skillId).remove();
                        $("#listItem" + skillType + skillId).remove();
                        $("#" + skillType + "SkillList").append('<option value="' + skillId + '">' + skillName + '</option>');

                        var options = $('#'+ skillType + 'SkillList option');
                        sortOptions(options);

                        $('select').material_select();
                    });
                    $('select').material_select();
                    $('.carousel').carousel('set', @Model.CarouselIndex);
                }
            });
        })
    });
</script>

MonsterHunterCompanion/Views/PalicoCompanion/_palico.cshtml
<svg width="110" height="200" xmlns="http://www.w3.org/2000/svg">
    <!-- Created with Method Draw - http://github.com/duopixel/Method-Draw/ -->
    <g>
        <title>Palico</title>
        <path id="palicoRightLeg" class="palico palicoLegs" d="m66.557402,118.704214c-3.986023,19.22506 -2.551527,23.96298 -4.532279,31.36269c-1.980752,7.39971 -0.026205,22.41679 6.043339,15.51565c6.069554,-6.90114 8.861627,-16.52017 10.152689,-24.92734c1.291062,-8.40718 4.923183,-30.37928 -1.095025,-27.84244" fill="#7B572D" />
        <path id="palicoLeftLeg" class="palico palicoLegs" d="m42.191697,117.572138c4.15709,19.22506 2.66103,23.96298 4.72679,31.36269c2.06576,7.39971 0.02733,22.41679 -6.3027,15.51565c-6.33004,-6.90114 -9.24194,-16.52017 -10.58841,-24.92734c-1.34647,-8.40718 -5.13447,-30.37928 1.14202,-27.84244" fill="#7B572D" />
        <path id="palicoRightArm" d="m63.110768,74.564599c14.070149,-8.72905 20.28172,-18.6875 22.642102,-26.51057c2.360382,-7.82308 7.684944,-22.25234 11.596972,-11.50944c3.912028,10.7429 -3.363584,23.93215 -9.166495,31.15923c-5.802911,7.22708 -21.036139,13.51429 -21.036139,13.19745" fill="#7B572D" />
        <path id="palicoLeftArm" d="m46.610744,73.064596c-16.9798,-8.72905 -24.4759,-18.6875 -27.3244,-26.51057c-2.8485,-7.82308 -9.27416,-22.25234 -13.99518,-11.50944c-4.72102,10.7429 4.05916,23.93215 11.06209,31.15923c7.00293,7.22708 25.38633,13.51429 25.38633,13.19745"  fill="#7B572D" />
        <path id="palicoRightEar" class="palico palicoEars" d="m80.782268,32.227338c3.942735,-8.088411 7.076152,-15.870927 6.01307,-16.699341c-1.06309,-0.828418 -10.361827,1.91997 -16.498579,3.39916c-6.136752,1.479191 6.542783,21.388595 10.485509,13.30018z" fill="#7B572D" />
        <path id="palicoLeftEar" class="palico palicoEars" d="m37.451317,17.562098c-7.128385,-2.471944 -13.929091,-4.258095 -14.530107,-3.195245c-0.601018,1.062859 2.521473,9.043253 4.301625,14.354029c1.780152,5.310776 17.35687,-8.686849 10.228482,-11.158784z" fill="#7B572D" />
        <path id="palicoBody" d="m26.886357,102.240557c4.336345,-21.001147 4.752447,-48.970485 26.640244,-46.923241c21.887797,2.047255 22.007072,25.505479 26.970912,45.440097c4.963851,19.934607 -1.530463,32.188425 -26.970912,31.350196c-25.440449,-0.838229 -30.976589,-8.865905 -26.640244,-29.867052z" fill="#d1b67d" />
        <ellipse id="palicoHead"  ry="26.575409" rx="28.325883" cy="39.305006" cx="53.45449" fill="#d1b67d" />
        <path id="palicoNose" class="palico palicoFacialFeatures" d="m44.773961,38.475948l8.297817,-9.071629l7.665465,9.663663c-4.644612,-1.446629 -10.476229,-1.479727 -15.963282,-0.592034z" fill="#7B572D" />
        <ellipse id="palicoLeftEye" class="palico palicoFacialFeatures" ry="2.731129" rx="2.731129" cy="31.771748" cx="36.043153" fill="#426373" />
        <ellipse id="palicoRightEye" class="palico palicoFacialFeatures" ry="2.731129" rx="2.731129" cy="31.771748" cx="69.901552" fill="#426373" />
        <ellipse id="palicoStomach" class="palico palicoMarking" ry="25.83784" rx="21.745174" cy="101.528951" cx="54.254818" fill="#d1b67d" />
        <ellipse id="palicoBigDot" class="palico palicoMarking" ry="7.776786" rx="8.000001" cy="105.491064" cx="53.714275" fill="#7B572D" />
        <ellipse id="palicoRightDot" class="palico palicoMarking" ry="3.571429" rx="3.428573" cy="95.476182" cx="42.031735" fill="#7B572D" />
        <ellipse id="palicoMiddleDot" class="palico palicoMarking" ry="3.571429" rx="3.428573" cy="90.714277" cx="53.714275" fill="#7B572D" />
        <ellipse id="palicoLeftDot" class="palico palicoMarking" ry="3.571429" rx="3.428573" cy="96.047611" cx="64.698403" fill="#7B572D" />
        </g>
</svg>

<script language="javascript">
    $(document).ready(function () {
        var TogglePalicoAnimation = function()
        {
            var playState = "running";
            if (palicoHead.style.animationPlayState == "running") {
                playState = "paused";
            }

            palicoRightLeg.style.animationPlayState = playState;
            palicoLeftLeg.style.animationPlayState = playState;
            palicoRightArm.style.animationPlayState = playState;
            palicoLeftArm.style.animationPlayState = playState;
            palicoRightEar.style.animationPlayState = playState;
            palicoLeftEar.style.animationPlayState = playState;
            palicoBody.style.animationPlayState = playState;
            palicoHead.style.animationPlayState = playState;
            palicoNose.style.animationPlayState = playState;
            palicoLeftEye.style.animationPlayState = playState;
            palicoRightEye.style.animationPlayState = playState;
            palicoStomach.style.animationPlayState = playState;
            palicoBigDot.style.animationPlayState = playState;
            palicoRightDot.style.animationPlayState = playState;
            palicoMiddleDot.style.animationPlayState = playState;
            palicoLeftDot.style.animationPlayState = playState;
        }

        TogglePalicoAnimation();

        $(".palico").click(function () {
            TogglePalicoAnimation();
        })
    });
</script>

MonsterHunterCompanion/Views/PalicoCompanion/_selectedSkills.cshtml
@{
    var addedSkillsId = Model + "Skills";
    var label = Model + " Skills";
    var listId = Model + "Equipped";
}
<div id="@addedSkillsId" class="input-field col s12">
    <ul class=" collection" id="@listId"></ul>
</div>

MonsterHunterCompanion/Views/PalicoCompanion/_villageProbabilities.cshtml
@model Dictionary<string, decimal>

<div class="input-field col s12">
    <ul class="collapsible" data-collapsible="accordion">

        @foreach (var key in Model.Keys)
        {
            <li>
                <div class="collapsible-header left-align">@key : @Math.Round(Model[key]*100,2)%</div>
                <div class="collapsible-body"><span>Lorem ipsum dolor sit amet.</span></div>
            </li>
        }
    </ul>
    <a id="calculateProbability" class="btn waves-effect waves-light">
        Calculate
    </a>
</div>

<script language="javascript">
    $(document).ready(function () {
       
        $("#calculateProbability").click(function () {
            $.ajax({
                url: "@Url.Action("CalculateProbabilities", "PalicoCompanion")",
                type: "POST",
                data: $('#palicoForm').serialize(),
                cache: false,
             
                success: function (result) {
                    $("#villageProbabilties").html(result);
                }
            })
        })
    });
</script>